# Generated by Django 5.0.7 on 2024-08-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='artists',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='playlists',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
